### ISSUE TITLE
The Lab is a Playground File

### ISSUE THREAD

**Issue by tjcarney89** [learn-co-curriculum/swift-dictIteration-lab#2]
The lab I'm getting is a playground file so I can't run any tests on it.

**Comment by JimCampagno** [comment]
Hey @tjcarney89 

Similar to what I had written in the other lab. You might have forked/cloned this lab down before I had updated it. 

Check this out on how to re-fork this lab to get your version up to date.

https://youtu.be/CsMDUFyyiNI
